apiVersion: oda.tmforum.org/v1beta1
coreFunction:
  dependantAPIs:
  - apitype: openapi
    id: TMF632
    isRequired: 'yes'
    name: PartyManagement
    resources:
    - individual:
      - GET
      - GET/id
    - organization:
      - GET
      - GET/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF672
    isRequired: 'yes'
    name: UserRolesandPermissions
    resources:
    - permission:
      - GET
      - GET/id
    - userRole:
      - GET
      - GET/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesandPermissions/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF669
    isRequired: 'yes'
    name: PartyRoleManagement
    resources:
    - partyRole:
      - GET
      - GET/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRoleManagement/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF620
    isRequired: 'no'
    name: ProductCatalogManagement
    resources:
    - productOffering:
      - GET
      - GET/id
    - productOfferingPrice:
      - GET
      - GET/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalogManagement/master/TMF620-ProductCatalogManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF637
    isRequired: 'no'
    name: ProductInventory
    resources:
    - product:
      - GET
      - GET/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF637_ProductInventory/master/TMF620-ProductInventory-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF667
    isRequired: 'no'
    name: DocumentManagement
    resources:
    - document:
      - GET
      - GET/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF667_DocumentManagement/master/TMF667-DocumentManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF701
    isRequired: not
    name: ProcessFlowManagement
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - DELETE
    - taskFlow:
      - PATCH
      - GET
      - GET /id
    specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF688
    isRequired: not
    name: Event
    resources:
    - event:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AgreementManagement/v4/docs
    id: TMF651
    implementation: /{{.Release.Name}}- agreemngtapi
    isRequired: 'yes'
    name: AgreementManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AgreementManagement/v4
    port: 8080
    resources:
    - agreement:
      - GET
      - GET/id
      - POST
      - PATCH/id
      - DELETE/id
    - agreementSpecification:
      - GET
      - GET/id
      - POST
      - PATCH/id
      - DELETE/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF651_AgreementManagement/master/TMF651-AgreementManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-procflowapi
    isRequired: not
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    processFlow:
    - POST
    - GET
    - GET /id
    - DELETE
    resources: null
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
    taskFlow:
    - PATCH
    - GET
    - GET /id
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-PromotionManagement
    isRequired: not
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
    port: 8080
    resources:
    - event:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
    version: 4
  publishedEvents:
  - apitype: openapi
    implementation: /{{.Release.Name}}-agreemngtapi
    name: userRole
    port: 80
    resources:
      agreement:
      - agreementCreateEvent
      - agreementAttributeValueChangeEvent
      - agreementStateChangeEvent
      - agreementSpecificationCreateEvent
      - agreementSpecificationAttributeValueChangeEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF651_AgreementManagement/master/TMF651-AgreementManagement-v4.0.0.swagger.json
  subscribedEvents:
  - apitype: openapi
    implementation: /{{.Release.Name}}-PartyManagement
    name: PartyManagement
    port: 80
    resources: party - individualDeleteEvent - organizationDeleteEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
kind: component
management: []
metadata:
  labels:
    oda.tmforum.org/componentName: TMFC020-agreementManagement
    oda.tmforum.org/funtionalBlockName: PartyManagement
  name: TMFC020-agreementManagement
reporting: []
security: []
spec:
  description: Agreement Management ODA-Component specification, from Open-API reference
    implementation.
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  type: TMFC020-agreementManagement
  version: 1.1.0
