apiVersion: oda.tmforum.org/v1beta1
coreFunction:
  dependantAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4/docs
    id: TMF634
    implementation: /{{.Release.Name}}-ResourceCatalog
    isRequired: true
    name: ResourceCatalogManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4.1.0
    port: 8080
    resources:
    - resourceCatalog:
      - GET
      - GET /id
    - resourceCategory:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - resourceSpecification:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - resourceCandidate:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - exportJob:
      - GET
      - POST
      - DELETE
    - importJob:
      - GET
      - POST
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF634_resourceCatalog/master/TMF634_resourceCatalog-v4.1.0.swagger.json
    version: 4.1
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4/docs
    id: TMF669
    implementation: /{{.Release.Name}}-PartyRole
    isRequired: not
    name: PartyRoleManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRole/v4.0
    port: 8080
    resources:
    - partyRole: -GET -GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/v4/docs
    id: TMF632
    implementation: /{{.Release.Name}}-Party
    isRequired: not
    name: Party
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/v4
    port: 8080
    resources:
    - individual:
      - GET
      - GET /id
    - organization:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_Party/master/TMF632-Party-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EntityCatalog/v4/docs
    id: TMF632
    implementation: /{{.Release.Name}}-EntityCatalog
    isRequired: not
    name: EntityCatalogManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EntityCatalog/v4
    port: 8080
    resources:
    - entitySpecification:
      - GET
      - GET /id
    - associationSpecification:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF662_EntityCatalog/master/TMF662-EntityCatalog-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-Event
    isRequired: not
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4
    port: 8080
    resources:
    - event:
      - POST
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-Event/master/TMF688-Event-v4.0.0.swagger.json
    version: 4
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4/docs
    id: TMF634
    implementation: /{{.Release.Name}}-ResourceCatalog
    isRequired: true
    name: ResourceCatalogManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4.1.0
    port: 8080
    resources:
    - resourceCatalog:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - resourceCategory:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - resourceSpecification:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - resourceCandidate:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - exportJob:
      - GET
      - GET /id
      - POST
      - DELETE
    - importJob:
      - GET
      - GET /id
      - POST
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF634_resourceCatalog/master/TMF634_resourceCatalog-v4.1.0.swagger.json
    version: 4.1
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-ProcessFlowManagement
    isRequired: not
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - DELETE
    - taskFlow:
      - PATCH
      - GET
      - GET /id
    specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-Event
    isRequired: not
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4
    port: 8080
    resources:
    - event:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-Event/master/TMF688-Event-v4.0.0.swagger.json
    version: 4
  publishedEvents:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4/docs
    id: TMF634
    implementation: /{{.Release.Name}}-ResourceCatalog
    isRequired: true
    name: ResourceCatalogManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4.1.0
    port: 8080
    resources:
    - ResourceCatalogManagement: null
    - resourceCatalogCreateEvent
    - resourceCatalogChangeEvent
    - resourceCatalogDeleteEvent
    - resourceCategoryCreateEvent
    - resourceCategoryChangeEvent
    - resourceCategoryDeleteEvent
    - resourceCandidateCreateEvent
    - resourceCandidateChangeEvent
    - resourceCandidateDeleteEvent
    - resourceSpecificationCreateEvent
    - resourceSpecificationChangeEvent
    - resourceSpecificationDeleteEvent
    - importJobCreateEvent
    - exportJobCreateEvent
    - exportJobStateChangeEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF634_resourceCatalog/master/TMF634_resourceCatalog-v4.1.0.swagger.json
    version: 4.1
  - -resources:
      ProcessFlowManagement:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
    implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
    name: ProcessFlowManagement
    port: 80
    specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
  subscribedEvents:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EntityCatalog/v4/docs
    id: TMF632
    implementation: /{{.Release.Name}}-EntityCatalog
    isRequired: not
    name: EntityCatalogManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EntityCatalog/v4
    port: 8080
    resources:
    - EntityCatalogManagement:
      - entitySpecificationCreateEvent
      - entitySpecificationAttributeValueChangeEvent
      - entitySpecificationStateChangeEvent
      - entitySpecificationDeleteEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF662_EntityCatalog/master/TMF662-EntityCatalog-v4.0.0.swagger.json
    version: 4
kind: component
management: []
metadata:
  labels:
    oda.tmforum.org/componentName: TMFC010-resourceCatalogManagement
    oda.tmforum.org/funtionalBlockName: Production
  name: TMFC010-resourcecatalogmanagement
reporting: []
security: []
spec:
  description: Resource Catalog Management component is responsible for organizing
    the collection of resource specifications that identify and define all requirements
    for a resource.
  maintainers:
  - email: elisabeth.andersson@matrixx.com
    name: Elisabeth Andersson
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  type: TMFC010-resourcecatalogmanagement
  version: 1.2.0
