apiVersion: oda.tmforum.org/v1beta1
coreFunction:
  dependantAPIs:
  - apitype: openapi
    id: TMF672
    isRequired: 'yes'
    name: UserRolesandPermissions
    resources:
    - permission:
      - GET
      - GET/id
    - role:
      - GET
      - GET/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesandPermissions/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF669
    isRequired: 'yes'
    name: PartyRoleManagement
    resources:
    - partyRole:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF673
    isRequired: 'no'
    name: GeographicAddressManagement
    resources:
    - GeographicAddress:
      - GET
      - GET /id
    - apitype: openapi
      id: TMF674
      isRequired: 'no'
      name: GeographicSiteManagement
      resources: null
      specification: https://github.com/tmforum-apis/TMF674-GeographicSiteManagement/blob/master/TMF674-GeographicSiteManagement-v4.0.0.swagger.json
      version: 4
    - GeographicSite:
      - GET
      - GET /id
    - apitype: openapi
      id: TMF675
      isRequired: 'no'
      name: GeographicLocationManagement
      resources: null
      specification: https://github.com/tmforum-apis/TMF675-GeographicLocationManagement/blob/master/TMF675-GeographicLocationManagement-v4.0.0.swagger.json
      version: 4
    - GeographicLocation:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF673-GeographicAddressManagement/blob/master/TMF673-GeographicAddressManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF701
    isRequired: not
    name: ProcessFlowManagement
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - DELETE
    - taskFlow:
      - PATCH
      - GET
      - GET /id
    specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF688
    isRequired: not
    name: Event
    resources:
    - event:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartnershipTypeManagement/v4/docs
    id: TMF668
    implementation: /{{.Release.Name}}-partnermngtapi
    isRequired: 'no'
    name: PartnershipTypeManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartnershipTypeManagement/v4
    port: 8080
    resources:
    - partnershipSpecification:
      - GET
      - GET/id
      - POST
      - PATCH/id
      - DELETE/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF668_PartnershipTypeManagement/master/TMF668-PartnershipTypeManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4/docs
    id: TMF632
    implementation: /{{.Release.Name}}-partymngtapi
    isRequired: 'yes'
    name: PartyManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4
    port: 8080
    resources:
    - individual:
      - GET
      - GET/id
      - POST
      - PATCH/id
      - DELETE/id
    - organization:
      - GET
      - GET/id
      - POST
      - PATCH/id
      - DELETE/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/CustomerManagement/v4/docs
    id: TMF629
    implementation: /{{.Release.Name}}-custmngtapi
    isRequired: 'no'
    name: CustomerManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/CustomerManagement/v4
    port: 8080
    resources:
    - customer:
      - GET
      - GET/id
      - POST
      - PATCH/id
      - DELETE/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF629_CustomerManagement/master/TMF629-CustomerManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-procmngttapi
    isRequired: 'no'
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    resources:
    - processFloe:
      - GET
      - GET/id
      - POST
      - DELETE/id
    - taskFlow:
      - GET
      - GET/id
      - PATCH/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-PromotionManagement
    isRequired: not
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
    port: 8080
    resources:
    - event:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
    version: 4
  publishedEvents:
  - apitype: openapi
    implementation: /{{.Release.Name}}-partnermngtapi
    name: PartnershipTypeMaagement
    port: 80
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF668_PartnershipTypeManagement/master/TMF668-PartnershipTypeManagement-v4.0.0.swagger.json
  - resources:
      Partnership:
      - PartnershipCreateEvent
      - PartnershipChangeEvent
      - PartnershipDeleteEvent
      PartnershipSpecification:
      - PartnershipSpecificationCreateEvent
      - PartnershipSpecificationChangeEvent
      - PartnershipSpecificationDeleteEvent
  - apitype: openapi
    implementation: /{{.Release.Name}}-partymngtapi
    name: partyManagement
    port: 80
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
  - resources:
      Individual:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
      Organization:
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
  - apitype: openapi
    implementation: /{{.Release.Name}}-custmngtapi
    name: CustomerManagement
    port: 80
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF629_CustomerManagement/master/TMF629-CustomerManagement-v4.0.0.swagger.json
  - resources:
      customer:
      - CustomerCreateEvent
      - CustomerAttributeValueChangeEvent
      - CustomerStateChangeEvent
      - CustomerDeleteEvent
  subscribedEvents:
  - apitype: openapi
    name: UserRolesandPermissions
    port: 80
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesandPermissions/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
  - resources UserRoles - UserRoleCreationNotification - UserRoleChangeNotification
  - apitype: openapi
    name: PartyRoleManagement
    port: 80
    specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
  - resources:
      artyRole:
      - PartyRoleCreateEvent
      - PartyRoleAttributeValueChangeEvent
      - PartyRoleStateChangeEvent
      - PartyRoleDeleteEvent
kind: component
management: []
metadata:
  labels:
    oda.tmforum.org/componentName: TMFC028-partyManagement
    oda.tmforum.org/funtionalBlockName: PartyManagement
  name: TMFC028-partymanagement
reporting: []
security: []
spec:
  description: Party management ODA-Component specification, from Open-API reference
    implementation.
  maintainers:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
    owners: null
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  type: TMFC028-partymanagement
  version: 1.1.0
