apiVersion: oda.tmforum.org/v1beta1
coreFunction:
  dependantAPIs:
  - apitype: openapi
    id: TMF632
    isRequired: 'yes'
    name: PartyManagement
    resources:
    - individual:
      - GET
      - GET/id
    - organization:
      - GET
      - GET/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF701
    isRequired: not
    name: ProcessFlowManagement
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - DELETE
    - taskFlow:
      - PATCH
      - GET
      - GET /id
    specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF688
    isRequired: not
    name: Event
    resources:
    - event:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRoleAndPermissionManagement/v4/docs
    id: TMF672
    implementation: /{{.Release.Name}}-userrole&permapi
    isRequired: 'yes'
    name: UserRoleAndPermission
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRoleAndPermissionManagement/v4
    port: 8080
    resources:
    - permission:
      - GET
      - GET/id
      - POST
      - PATCH/id
      - DELETE/id
    - userRole:
      - GET
      - GET/id
      - POST
      - PATCH/id
      - DELETE/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRoleAndPermission/master/TMF672-UserRoleAndPermission-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4/docs
    id: TMF669
    implementation: /{{.Release.Name}}-partyroleapi
    isRequired: 'yes'
    name: PartyRoleManagement
    partyRole:
    - GET
    - GET/id
    - POST
    - PATCH/id
    - DELETE/id
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4
    port: 8080
    resources: null
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRoleManagement/master/TMF672-PartyRoleManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-PromotionManagement
    isRequired: not
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
    port: 8080
    resources:
    - event: null
    - GET
    - GET /id
    - POST
    - PATCH
    - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
    version: 4
  publishedEvents:
  - apitype: openapi
    implementation: /{{.Release.Name}}-userrole&permapi
    name: userRole
    port: 80
    resources:
      permission:
      - permissionCreateEvent
      - permissionAttributeValueChangeEvent
      - permissionStateChangeEvent
      - permissionDeleteEvent
      userRole:
      - userRoleCreateEvent
      - userRoleAttributeValueChangeEvent
      - userRoleStateChangeEvent
      - userRoleDeleteEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRoleAndPermission/master/TMF672-UserRoleAndPermission-v4.0.0.swagger.json
  - apitype: openapi
    implementation: /{{.Release.Name}}-partyroleapi
    name: partyRole
    port: 80
    resources:
      partyRole:
      - PartyRoleCreateEvent
      - PartyRoleAttributeValueChangeEvent
      - PartyRoleStateChangeEvent
      - PartyRoleDeleteEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRoleManagement/master/TMF672-PartyRoleManagement-v4.0.0.swagger.json
  subscribedEvents:
  - apitype: openapi
    implementation: /{{.Release.Name}}-PartyManagement
    name: PartyManagement
    port: 80
    resources:
    - organizationCreateEvenet
    - organizationAttributeValueChangeEvent
    - organizationStateChangeEvent
    - individualCreateEvent
    - individualAttributeValueChangeEvent
    - individualStateChangeEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
  - apitype: openapi
    implementation: /{{.Release.Name}}-ProcessFlowManagement
    name: ProcessFlowManagement
    port: 80
    resources:
    - processFlowCreateEvent
    - processFlowStateChangeEvent
    - taskFlowCreateEvent
    - taskFlowStateChangeEvent
    specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
kind: component
management: []
metadata:
  labels:
    oda.tmforum.org/componentName: TMFC035-partyRolesAndPermissionsManagement
    oda.tmforum.org/funtionalBlockName: PartyManagement
  name: TMFC035-partyroles&permissionsmanagement
reporting: []
security: []
spec:
  description: Party Roles & Permissions ODA-Component specification, from Open-API
    reference implementation.
  maintainers:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
    owners: null
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  type: TMFC035-partyroles&permissionsmanagement
  version: 1.1.0
