apiVersion: oda.tmforum.org/v1beta1
coreFunction:
  dependantAPIs:
  - apitype: openapi
    id: TMF632
    isRequired: not
    name: PartyManagement
    resources:
    - individual:
      - GET
    - organization:
      - GET
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-Party-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF669
    isRequired: not
    name: PartyRoleManagement
    resources:
    - PartyRoleManagement:
      - GET
    specification: https://github.com/tmforum-apis/TMF669_PartyRole/blob/master/TMF669-PartyRole-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF620
    isRequired: not
    name: ProductCatalogManagement
    resources:
    - GET
    - GET /id
    - POST
    - PATCH
    - DELETE
    specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF651
    isRequired: not
    name: AgreementManagement
    resources:
    - agreement:
      - GET
      - GET /id
    - agreementSpecification:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF651_AgreementManagement/blob/master/TMF651-Agreement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF648
    name: QuoteManagement
    resources:
    - Quote:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF688
    isRequired: not
    name: Event
    resources:
    - event:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF622
    isRequired: not
    name: ProductOrder
    resources:
    - ProductOrder:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF701
    isRequired: not
    name: ProcessFlowManagement
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - DELETE
    - taskFlow:
      - PATCH
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4.0
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/v4/docs
    id: TMF699
    implementation: /{{.Release.Name}}-SalesManagement
    isRequired: true
    name: SalesManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/v4
    port: 8080
    resources:
    - SalesLead:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - SalesOpportunity:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF699_SalesManagement/master/TMF699-SalesManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-ProcessFlowManagement
    isRequired: not
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - DELETE
    - taskFlow:
      - PATCH
      - GET
      - GET /id
    specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-PromotionManagement
    isRequired: not
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
    port: 8080
    rerouces:
    - event:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
    version: 4.0
  publishedEvents:
  - -resources:
      SalesLead:
      - SalesLeadCreateEvent
      - SalesLeadAttributeValueChangeEvent
      - SalesLeadStateChangeEvent
      - SalesLeadDeleteEvent
      - productSpecificationCreate
      SalesOpportunity:
      - SalesOpportunityCreateEvent
      - SalesOpportunityAttributeValueChangeEvent
      - SalesOpportunityStateChangeEvent
      - SalesOpportunityDeleteEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/hub
    implementation: /{{.Release.Name}}-SalesManagement
    name: SalesManagement
    port: 80
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF699_SalesManagement/master/TMF699-SalesManagement-v4.0.0.swagger.json
  - -resources:
      ProcessFlowManagement:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
    implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
    name: ProcessFlowManagement
    port: 80
    specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
  subscribedEvents:
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/call-back
    implementation: /{{.Release.Name}}-PartyManagement
    name: PartyManagement
    port: 80
    resources:
    - Individual:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
    - Organization:
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
    specification: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductCatalogManagement/call-back
    implementation: /{{.Release.Name}}-ProductCatalogManagement
    name: ProductCatalogManagement
    port: 80
    resources:
    - ProductOffering:
      - ProductOfferingCreateEvent
      - ProductOfferingAttributeValueChangeEvent
      - ProductOfferingStateChangeEvent
      - ProductOfferingDeleteEvent
    - ProductSpecification:
      - ProductSpecificationCreateEvent
      - ProductSpecificationAttributeValueChangeEvent
      - ProductSpecificationStateChangeEvent
      - ProductSpecificationDeleteEvent
    - ProductOfferingPrice:
      - ProductOfferingPriceCreateEvent
      - ProductOfferingPriceAttributeValueChangeEvent
      - ProductOfferingPriceStateChangeEvent
      - ProductOfferingPriceDeleteEvent
    specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductCatalogManagement/call-back
    implementation: /{{.Release.Name}}-ProductOrder
    name: ProductOrder
    port: 80
    resources:
    - ProductOrder:
      - ProductOrderCreateEvent
      - ProductOrderAttributeValueChangeEvent
      - ProductOrderDeleteEvent
      - ProductOrderStateChangeEvent
      - ProductOrderInformationRequiredEvent
    specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/ProductOrder/TMF622-ProductOrder-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Agreement/call-back
    implementation: /{{.Release.Name}}-Agreement
    name: AgreementManagement
    port: 80
    resources:
    - Agreement:
      - AgreementCreateEvent
      - AgreementAttributeValueChangeEvent
      - AgreementStateChangeEvent
      - AgreementDeleteEvent
    - AgreementSpecification:
      - AgreementSpecificationCreateEvent
      - AgreementSpecificationAttributeValueChangeEvent
      - AgreementSpecificationStateChangeEvent
      - AgreementSpecificationDeleteEvent
    specification: https://github.com/tmforum-apis/TMF651_AgreementManagement/blob/master/TMF651-Agreement-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/QuoteManagement/call-back
    implementation: /{{.Release.Name}}-QuoteManagement
    name: QuoteManagement
    port: 80
    resources:
    - Quote:
      - QuoteCreateEvent
      - QuoteStateChangeEvent
      - QuoteDeleteEvent
      - QuoteInformationRequiredEvent
      - QuoteAttributeValueChangeEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/call-back
    implementation: /{{.Release.Name}}-PartyRoleManagement
    name: PartyRoleManagement
    port: 80
    resources:
    - PartyRole:
      - PartyRoleCreateEvent
      - PartyRoleAttributeValueChangeEvent
      - PartyRoleStateChangeEvent
      - PartyRoleDeleteEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
kind: component
management: []
metadata:
  labels:
    oda.tmforum.org/componentName: TMFC036-LeadAndOpportunityManagement
    oda.tmforum.org/funtionalBlockName: Party Management
  name: TMFC036 - Lead and Opportunity Management
reporting: []
security: []
spec:
  description: Simple Lead and Opportunity Management ODA-Component from Open-API
    reference implementation.
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  type: TMFC036 - Lead and Opportunity Management
  version: 1.1.0
