apiVersion: oda.tmforum.org/v1beta1
coreFunction:
  PublishedEvent:
    AlarmManagement:
    - alarmStateChange**
    - alarmCreateEvent**
    - alarmClearEvent**
    - alarmAckEvent**
    PerformanceManagement:
    - measurementCollectionJobCreateEvent
    - measurementCollectionJobExecutionStateChangeEvent
    - measurementCollectionJobDeleteEvent
    - measurementCollectionJobAttributeValueChangeEvent
    - measurementCollectionJobFilesReadyEvent
    - measurementCollectionJobFilesPreparationErrorEvent
    - onDemandCollectionCreateEvent
    - onDemandCollectionExecutionStateChangeEvent
    - onDemandCollectionDeleteEvent
    - onDemandCollectionAttributeValueChangeEvent
    - onDemandCollectionFilesReadyEvent
    - onDemandCollectionFilesPreparationErrorEvent
    PerformanceThresholdManagement:
    - thresholdCreateNotification
    - thresholdChangeNotification
    - thresholdRuleCreateNotification
    - thresholdRuleChangedNotification
    - thresholdJobCreateNotification
    - thresholdJobChangedNotification
    - thresholdJobSuspendNotification
    - thresholdJobResumeNotification
    ProcessFlowManagement:
    - processFlowCreateEvent
    - processFlowStateChangeEvent
    - processFlowStateDeleteEvent
    - processFlowStateAttributeValueChangeEvent
    - taskFlowCreateEvent
    - taskFlowStateChangeEvent
    - taskFlowDeleteEvent
    - taskFlowAttributeValueChangeEvent
    - taskFlowInformationRequiredEvent
  SubscribedEvent:
    ProcessFlowManagement:
    - processFlowCreateEvent
    - processFlowStateChangeEvent
    - taskFlowCreateEvent
    - taskFlowStateChangeEvent
    ResourceCatalogManagement:
    - ResourceSpecificationChangeEvent
    ResourceInventoryManagement:
    - ResourceCreateEvent
    - ResourceAttributeValueChangeEvent
    - ResourceStateChangeEvent
    - ResourceDeleteEvent
  dependantAPIs:
  - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceManagement/v4/docs
    implementation: /{{.Release.Name}}-PerformanceManagement
    name: PerformanceManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceManagement/v4
    port: 8080
    required: true
    specification: https://github.com/tmforum-apis/TMF628_Performance/blob/main/TMF628-Performance-v4.0.0.swagger.json
    version: 4.0.0
  - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
    implementation: /{{.Release.Name}}-ResourceInventory
    name: ResourceInventory
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4
    port: 8080
    specification: https://github.com/tmforum-apis/TMF639_ResourceInventory/blob/master/TMF639-ResourceInventory-v4.0.0.swagger.json
    version: 4.0.0
  - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagementt/v4/docs
    implementation: /{{.Release.Name}}-GeographicAddressManagement
    name: GeographicAddressManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4
    port: 8080
    specification: https://github.com/tmforum-apis/TMF673_GeographicAddress/blob/master/TMF673-GeographicAddress-v4.0.1.swagger.json
    version: 4.0.1
  - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4/docs
    implementation: /{{.Release.Name}}-GeographicSiteManagement
    name: GeographicSiteManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4
    port: 8080
    specification: https://github.com/tmforum-apis/TMF674_GeographicSite/blob/master/TMF674-GeographicSite-v4.0.0.swagger.json
    version: 4.0.0
  - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    implementation: /{{.Release.Name}}-ProcessFlowManagement
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    specification: https://github.com/tmforum-apis/TMF701-ProcessFlowManagement/blob/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
    version: 4.0.0
  - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4/docs
    implementation: /{{.Release.Name}}-EventManagement
    name: EventManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4
    port: 8080
    specification: https://github.com/tmforum-apis/TMF688-EventManagement/blob/master/TMF688-EventManagement-v4.0.0.swagger.json
    version: 4.0.0
  eventNotification: null
  exposedAPIs:
  - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceManagement/v4/docs
    id: TMF628
    implementation: /{{.Release.Name}}-PerformanceManagement
    name: PerformanceManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceManagement/v4
    port: 8080
    required: true
    specification: https://github.com/tmforum-apis/TMF628_Performance/blob/main/TMF628-Performance-v4.0.0.swagger.json
    version: 4.0.0
  - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AlarmManagement/v4/docs
    id: TMF642
    implementation: /{{.Release.Name}}-AlarmManagement
    name: AlarmManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AlarmManagement/v4
    port: 8080
    required: true
    specification: https://github.com/tmforum-apis/TMF642_AlarmManagement/blob/master/TMF642-Alarm-v4.0.0.swagger.json
    version: 4.0.0
  - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/processFlowManagement/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-ProcessFlowManagement
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/processFlowManagement/v4
    port: 8080
    specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4.0.0
  - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-EventManagement
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4
    port: 8080
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-EventManagement-v4.0.0.swagger.json
    version: 4.0.0
  managementAPIs: null
kind: component
management: []
metadata:
  labels:
    oda.tmforum.org/componentName: TMFC038-resourcePerformanceManagement
    oda.tmforum.org/funtionalBlockName: IntelligenceManagement
  name: TMFC038-resourceperformancemanagement
reporting: []
security: []
spec:
  description: Simple Resource Performance Management ODA-Component from Open-API
    reference implementation.
  maintainers:
  - email: milind.2.bhagwat@bt.com
    name: Milind Bhagwat
  owners:
  - email: milind.2.bhagwat@bt.com
    name: Milind Bhagwat
  type: TMFC038-resourceperformancemanagement
  version: 0.0.1
