apiVersion: oda.tmforum.org/v1beta1
coreFunction:
  dependantAPIs:
  - apitype: openapi
    id: TMF633
    isRequired: not
    name: ServiceCatalogManagement
    resources:
    - serviceSpecification:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF669
    isRequired: not
    name: PartyRoleManagement
    resources:
    - PartyRoleManagement:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF672
    isRequired: not
    name: ResourceCatalog
    resources:
    - resourceSpecification:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-ResourceCatalog/master/TMF688-ResourceCatalog-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF651
    isRequired: not
    name: AgreementManagement
    resources:
    - agreement:
      - GET
      - GET /id
    - agreementSpecification:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF651_AgreementManagement/blob/master/TMF651-Agreement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF673
    name: GeographicAddressManagement
    resources:
    - geographicAddress:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF673_GeographicAddress/blob/master/TMF673-GeographicAddress-v4.0.1.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF674
    name: GeographicSiteManagement
    resources:
    - geographicSite:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF674_GeographicSite/blob/master/TMF674-GeographicSite-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF675
    name: GeographicLocation
    resources:
    - geographicLocation:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF675_GeographicLocation/blob/master/TMF675-GeographicLocation-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF672
    isRequired: not
    name: UserRolePermission
    resources:
    - permission:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF672_UserRolesPermissions/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF662
    isRequired: not
    name: EntityCatalogManagement
    resources:
    - entitySpecification:
      - GET
      - GET /id
    - associationSpecification:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF662_EntityCatalog/blob/master/TMF662-EntityCatalog-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF620
    isRequired: not
    name: ProductCatalogManagement
    resources:
    - GET
    - GET /id
    - POST
    - PATCH
    - DELETE
    specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF688
    isRequired: not
    name: Event
    resources:
    - event:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4.0
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productCatalogManagement/v4/docs
    id: TMF620
    implementation: /{{.Release.Name}}-prodcatapi
    isRequired: true
    name: productcatalogmanagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productCatalogManagement/v4
    port: 8080
    resources:
    - catalog:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - category:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - productSpecification:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - productOffering:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - productOfferingPrice:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    - exportJob:
      - POST
      - GET
      - GET /id
      - DELETE
    - importJob:
      - POST
      - GET
      - GET /id
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-ProcessFlowManagement
    isRequired: not
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - DELETE
    - taskFlow:
      - PATCH
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
    id: TMF671
    implementation: /{{.Release.Name}}-PromotionManagement
    isRequired: true
    name: PromotionManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
    port: 8080
    resource:
    - promotion:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-PromotionManagement
    isRequired: not
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
    port: 8080
    resources:
    - event:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
    version: 4.0
  publishedEvents:
  - -resources:
      ProductCatalogManagement:
      - productSpecificationCreate
      - productSpecificationDeleteEvent
      - categoryCreateEvent
      - categoryDeleteEvent
      - productOfferingCreateEvent
      - productOfferingAttributeValueChangeEvent
      - productOfferingStateChangeEvent
      - productOfferingDeleteEvent
      - productOfferingPriceCreateEvent
      - productOfferingPriceAttributeValueChangeEvent
      - productOfferingPriceStateChangeEvent
      - productOfferingPriceDeleteEvent
      - catalogCreateEvent
      - catalogDeleteEvent
      - catalogBatchEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productspecification/hub
    implementation: /{{.Release.Name}}-ProductCatalogManagementEvent
    name: ProductCatalogManagement
    port: 80
    specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
  - -resources:
      PromotionManagement:
      - promotionCreateEvent
      - promotionDeleteEvent
      - promotionAttributeValueChangeEvent
      - promotionStateChangeEvent
      - promotionInformationRequiredEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagementEvent/hub
    implementation: /{{.Release.Name}}-PromotionManagementEvent
    name: PromotionManagement
    port: 80
    specification: https://github.com/tmforum-apis/TMF671_Promotion/blob/master/TMF671-Promotion-v4.0.0.swagger.json
  - -resources:
      ProcessFlowManagement:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
    implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
    name: ProcessFlowManagement
    port: 80
    specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
  subscribedEvents:
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicespecification/call-back
    implementation: /{{.Release.Name}}-ResourceActivationAndConfiguration
    name: ResourceActivationAndConfiguration
    port: 80
    resources:
    - ResourceActivationAndConfiguration:
      - resourceChangeEvent
      - monitorCreateEvent
      - monitorStatechangeEvent
    specification: https://open-api.tmforum.org/TMF633-Servicecatalog-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicespecification/call-back
    implementation: /{{.Release.Name}}-ServiceCatalogManagement
    name: ServiceCatalogManagement
    port: 80
    resources:
    - ServiceCatalogManagement:
      - serviceSpecificationStateChange
      - serviceSpecificationAttributeValueChangeEvent
      - serviceSpecificationCreateEvent
      - serviceSpecificationDeleteEvent
    - ResourceCatalog:
      - resourceSpecificationCreateEvent
      - resourceSpecificationChangeEvent
      - resourceSpecificationDeleteEvent
    specification: https://open-api.tmforum.org/TMF633-Servicecatalog-v4.0.0.swagger.json
kind: component
management: []
metadata:
  labels:
    oda.tmforum.org/componentName: TMFC001-productcatalogManagement
    oda.tmforum.org/funtionalBlockName: CoreCommerce
  name: TMFC001-productcatalogmanagement
reporting: []
security: []
spec:
  description: Simple Product Catalog ODA-Component from Open-API reference implementation.
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  type: TMFC001-productcatalogmanagement
  version: 1.1.0
