apiVersion: oda.tmforum.org/v1beta1
coreFunction:
  dependantAPIs:
  - apitype: openapi
    id: TMF632
    isRequired: 'yes'
    name: PartyManagement
    resources:
    - individual:
      - GET
      - GET/id
    - organization:
      - GET
      - GET/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF669
    isRequired: 'yes'
    name: PartyRoleManagement
    resources:
    - partyRole:
      - POST
    specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF701
    isRequired: 'no'
    name: ProcessFlowManagement
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - DELETE
    - taskFlow:
      - PATCH
      - GET
      - GET /id
    specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    id: TMF688
    isRequired: 'no'
    name: Event
    resources:
    - event:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/DigitalIdentityManagement/v4/docs
    id: TMF720
    implementation: /{{.Release.Name}}-digidemngt
    isRequired: 'yes'
    name: DigitalIdentityManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/DigitalIdentityManagement/v4
    port: 8080
    resources:
    - digitalIdentity:
      - GET
      - GET/id
      - POST
      - PATCH/id
      - DELETE/id
    - roles:
      - GET
      - GET/id
      - POST
      - PATCH/id
      - DELETE/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF720_DigitalIdentityManagement/master/TMF720-DigitalIdentityManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-procmngttapi
    isRequired: 'no'
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    resources:
    - processFlow:
      - GET
      - GET/id
      - POST
      - DELETE/id
    - taskFlow:
      - GET
      - GET/id
      - PATCH/id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
    version: 4
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-PromotionManagement
    isRequired: not
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
    port: 8080
    resources:
    - event:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
    version: 4
  publishedEvents:
  - apitype: openapi
    implementation: /{{.Release.Name}}-digidemngt
    name: digitalIdentity
    port: 80
    resources:
      DigitalIdentity:
      - DigitalIdentityCreateEvent
      - DigitalIdentityStateChangeEvent
      - DigitalIdentityDeleteEvent
      - DigitalIdentityAttributeValueChangeEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF720_DigitalIdentityManagement/master/TMF720-DigitalIdentityManagement-v4.0.0.swagger.json
  subscribedEvents:
  - apitype: openapi
    name: PartyRoleManagement
    port: 80
    resources: userRoles - UserRoleCreationNotification - UserRoleChangeNotification
    specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
kind: component
management: []
metadata:
  labels:
    oda.tmforum.org/componentName: TMFC020-digitalIdentityManagement
    oda.tmforum.org/funtionalBlockName: PartyManagement
  name: TMFC020-digitalidentitymanagement
reporting: []
security: []
spec:
  description: Digital Identity management ODA-Component specification, from Open-API
    reference implementation.
  maintainers:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
    owners: null
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  type: TMFC020-digitalidentitymanagement
  version: 1.1.0
