name: Build ODA specs

on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'Branch name'
        required: true
        default: 'v1beta2'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout build repository
      uses: actions/checkout@v4
      with:
        path: TMForum-ODA-Asset-Build

    - name: Checkout component spec repository
      uses: actions/checkout@v4
      with:
        path: TMForum-ODA-Component-Specification
        repository: tmforum-rand/TMForum-ODA-Component-Specification
        token: ${{ secrets.DEVOPS_TOKEN }}
        ref: ${{ inputs.ref_name }}
        sparse-checkout: |
          specifications
          .gitignore

    - name: Checkout canvas repository
      uses: actions/checkout@v4
      with:
        repository: tmforum-rand/TMForum-ODA-Canvas-Specification
        path: TMForum-ODA-Canvas-Specification
        token: ${{ secrets.DEVOPS_TOKEN }}
        ref: ${{ inputs.ref_name }}
        sparse-checkout: |
          src/supporting-functions
          .gitignore
        

    - name: Checkout release repository
      uses: actions/checkout@v4
      with:
        repository: tmforum-rand/TMForum_ODA_Component_Conformance
        path: TMForum_ODA_Component_Conformance
        token: ${{ secrets.DEVOPS_TOKEN }}
        ref: ${{ inputs.ref_name }}

    - name: Run build script
      run: cd $GITHUB_WORKSPACE/TMForum-ODA-Asset-Build && python3 CI/tasks/addSuportingFunctions.py 

    - name: Commit and push changes
      run: |
        cd $GITHUB_WORKSPACE/TMForum_ODA_Component_Conformance

        # Check for changes
        if [[ `git status --porcelain` ]]; then
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update from GitHub Actions"
          git push
        else
          echo "No changes to commit"
        fi
